//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubjectSelectionPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjectselection
    {
        public int Id { get; set; }
        public string Studentid { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public int Semester { get; set; }
        public string Dept { get; set; }
        public string Subject { get; set; }
        public string Comments { get; set; }
    }
}
